
export default function createGallery(){
  $('body').append($('<div\n'
    + '  id="blueimp-gallery"\n'
    + '  class="blueimp-gallery blueimp-gallery-controls"\n'
    + '  aria-label="image gallery"\n'
    + '  aria-modal="true"\n'
    + '  role="dialog"\n'
    + '  data-continuous="false"\n'
    + '>\n'
    + '  <div class="slides" aria-live="polite"></div>\n'
    + '  <h3 class="title"></h3>\n'
    + '  <a\n'
    + '    class="prev"\n'
    + '    aria-controls="blueimp-gallery"\n'
    + '    aria-label="previous slide"\n'
    + '    aria-keyshortcuts="ArrowLeft"\n'
    + '  ></a>\n'
    + '  <a\n'
    + '    class="next"\n'
    + '    aria-controls="blueimp-gallery"\n'
    + '    aria-label="next slide"\n'
    + '    aria-keyshortcuts="ArrowRight"\n'
    + '  ></a>\n'
    + '  <a\n'
    + '    class="close"\n'
    + '    aria-controls="blueimp-gallery"\n'
    + '    aria-label="close"\n'
    + '    aria-keyshortcuts="Escape"\n'
    + '  ></a>\n'
    + '  <ol class="indicator"></ol>\n'
    + '</div>'))
}
